language: csharp
sudo: required
mono: none
dist: xenial
dotnet: 2.2
install:
  - nvm install v11.12.0
  - nvm use 11.12.0
services: postgresql
addons:
  postgresql: "10"
  apt:
    sources:
      - google-chrome
    packages:
      - postgresql-10
      - postgresql-client-10
      - ng-common
      - google-chrome-stable
env:
  global:
    - PGPORT=5432


jobs:
    include:
        - stage: create tables with dotnet
          before_script:
              - psql -c "CREATE DATABASE clientserver;" -U postgres
              - psql -c "CREATE USER clientserver WITH ENCRYPTED PASSWORD 'password';" -U postgres
              - psql -c 'GRANT ALL PRIVILEGES ON DATABASE clientserver TO clientserver;' -U postgres
              - cd hook_system/client/ClientServer
          script:
              - dotnet ef migrations add InitialCreate
              - dotnet ef database update
              - dotnet restore
              - dotnet build
        - stage: initialize angular
          before_script:
              - cd hook_system/client/ClientServer/ClientApp
              - npm install -g @angular/cli
	      - npm install -g @angular-devkit/build-angular
          script:
              - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
              - npm run e2e -- --protractor-config=e2e/protractor.conf.js
        - stage: run scub
          before_script:
              - cd hook_system/client/ClientServer/scrubbing
              - virtualenv env
              - source env/scripts/activate
              - pip install -r requirements.txt
          script:
              -  python3 scrub.py ~/test-harness/Year/2018-2019/Fall/COSC/1P02/A1\
        - stage: run client server and portal
          before_script:
              - cd hook_system/client/ClientServer/
          script:
              - dotnet run
