language: csharp
sudo: required
mono: none
dist: xenial
dotnet: 2.2
install:
  - nvm install v11.12.0
  - nvm use 11.12.0
services: postgresql
addons:
  postgresql: "10"
  chrome: stable
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
      - ng-common
env:
  global:
    - PGPORT=5432


jobs:
    include:
        - stage: create tables with dotnet and run python script
          before_script:
              - psql -c "CREATE DATABASE clientserver;" -U postgres
              - psql -c "CREATE USER clientserver WITH ENCRYPTED PASSWORD 'password';" -U postgres
              - psql -c 'GRANT ALL PRIVILEGES ON DATABASE clientserver TO clientserver;' -U postgres
              - sudo apt-get update
              - sudo apt-get install python3
              - sudo apt-get install python3-pip
              - cd hook_system/client/ClientServer/scrubbing
              - pip3 install --user -r requirements.txt
              - mkdir tmp
              - cd ../
          script:
              - dotnet ef migrations add InitialCreate
              - dotnet ef database update
              - dotnet restore
              - dotnet build

        - stage: initialize angular
          before_script:
              - cd hook_system/client/ClientServer/ClientApp
              - npm install
          script:
              - npm run test
        - stage: run python unittests
          before_script:
              - sudo apt-get update
              - sudo apt install software-properties-common
              - sudo add-apt-repository ppa:deadsnakes/ppa -y
              - sudo apt update
              - sudo apt install -y python3.7 python3-pip python3-setuptools python3-virtualenv libpython3.7-dev
              - cd hook_system/processor/Src
              - virtualenv -p /usr/bin/python3.7 env
              - source env/bin/activate
              - sudo -H pip3 install --upgrade pip
              - pip3 install git+https://github.com/yaml/pyyaml.git
              - pip3 install -r ../requirements.txt
          script:
              - python3.7 hook_suite.py

